#!/usr/bin/env sh
# 上边是Shebang 行，是指在脚本文件的开头的一行特殊注释，用于告诉操作系统应该使用哪个解释器来执行该脚本。通常的格式是 #!/path/to/interpreter，其中 #! 是一个固定的标记，后面跟着解释器的路径。
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
# 在项目中执行 Git 钩子（hooks）
# 执行 Git 钩子（hooks）是指在 Git 特定的操作发生时自动运行预定义的脚本。
# Git 钩子包括诸如 pre-commit、post-commit、pre-push、post-merge 等等，每个钩子在 Git 的不同操作点被触发。
# 一句话："pre-commit" 文件的作用是在执行 Git 提交操作之前自动运行指定的脚本或命令，通常用于执行代码风格检查、静态代码分析等任务。

